In [1]:
import torch


In [5]:
x=torch.arange(12)
x
#我们可以使用 arange 创建一个行向量 x。这个行向量包含以0开始的前12个整数，它们默认创建为整数。

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x.shape
#通过张量的shape属性来访问张量（沿每个轴的长度）的形状 。

torch.Size([12])

In [8]:
x.numel()
#只想知道张量中元素的总数，即形状的所有元素乘积，可以检查它的大小（size）。

12

In [9]:
X=x.reshape(3,4)
X
#要想改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数。
# 例如，可以把张量x从形状为（12,）的行向量转换为形状为（3,4）的矩阵。
#通过改变张量的形状，张量的大小不变
#x.reshape(3,-1)或x.reshape(-1,4)可取代x.reshape(3,4)
#通过-1来自动计算维度

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
torch.zeros((2,3,4))
#创建一个(2,3,4)的张量，其中所有元素设置为0

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2,3,4))
#创建一个形状为(2,3,4)的张量，其中所有元素都设置为1

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
torch.randn(3,4)
#创建一个形状为(3,4)的张量，其中每个元素都从均值为0、标准差为1的标准高斯分布(正态分布)中随机采样

tensor([[-0.6115,  0.5314, -0.9080, -0.9518],
        [ 1.2875, -0.1555,  1.5028,  0.3376],
        [-0.3506, -1.1761, -0.6068,  0.9434]])

In [13]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
#通过提供包含数值的python列表(或嵌套列表)，来为所需张量中的每个元素赋予确定值
#最外层的列表对应于轴0，内层的列表对应于轴1

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])