In [ ]:
#2.1.2运算符

In [3]:
import torch

In [2]:
x=torch.tensor([1.0,2,3,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y #**求幂

(tensor([ 3.,  4.,  5., 10.]),
 tensor([-1.,  0.,  1.,  6.]),
 tensor([ 2.,  4.,  6., 16.]),
 tensor([0.5000, 1.0000, 1.5000, 4.0000]),
 tensor([ 1.,  4.,  9., 64.]))

In [3]:
torch.exp(x)
#exp(x)

tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 2.9810e+03])

In [4]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]]) #为所需张量中的每个元素赋予确定值
#torch.cat()多个张量连接在一起  （轴-0  按行 dim=0） （轴-1 按列 dim=1）   
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1) #dim=0  

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [8]:
X==Y
#对X，Y中每个位置 进行一一对比  相等为true  否则为false

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [9]:
X.sum()
#对张量中所有元素进行求和

tensor(66.)

In [ ]:
#2.1.3广播机制

#通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
#对生成的数组执行按元素操作。

In [10]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [12]:
a+b
#由于a和b分别是3*1和1*2矩阵，a+b  则  矩阵将复制列  矩阵b将复制行  然后按照元素相加


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
#2.1.4.索引和切片

#张量中的元素可以通过索引访问。 
#与任何Python数组一样：第一个元素的索引是0，最后一个元素索引是-1；
#可以指定范围以包含第一个元素和最后一个之前的元素。

In [5]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))